services:
  server:
    working_dir: /app
    image: node:latest
    command: npm start
    volumes:
      - ./app:/app
    ports:
      - 8100:8100
    restart: always
    depends_on:
      - db
  db:
    image: mongo:latest
    restart: always
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=app

